php:
  image: dockerizedrupal/php-5.2:1.0.3
  hostname: php
  ports:
    - "9000:9000"
  environment:
    - SERVER_NAME=localhost
    - DRUPAL_VERSION=6
    - PHP_INI_REALPATH_CACHE_SIZE=256k
    - PHP_INI_REALPATH_CACHE_TTL=3600
    - PHP_INI_POST_MAX_SIZE=512M
    - PHP_INI_TIMEZONE=UTC
    - PHP_INI_UPLOAD_MAX_FILESIZE=512M
    - PHP_INI_SHORT_OPEN_TAG=On
    - PHP_INI_MAX_EXECUTION_TIME=300
    - PHP_INI_MAX_INPUT_VARS=4096
    - PHP_INI_MEMORY_LIMIT=512M
    - PHP_INI_DISPLAY_ERRORS=On
    - PHP_INI_DISPLAY_STARTUP_ERRORS=On
    - PHP_INI_ERROR_REPORTING=E_ALL
    - PHP_INI_EXPOSE_PHP=On
    - PHP_INI_ALLOW_URL_FOPEN=On
    - PHP_INI_OPCACHE=On
    - PHP_INI_OPCACHE_MEMORY_CONSUMPTION=2048
    - PHP_INI_XDEBUG=On
    - PHP_INI_XDEBUG_REMOTE_PORT=9000
    - PHP_INI_XDEBUG_REMOTE_HOST=127.0.0.1
    - PHP_INI_XDEBUG_REMOTE_CONNECT_BACK=On
    - PHP_INI_XDEBUG_IDEKEY=PHPSTORM
    - PHP_INI_MEMCACHED=On
    - PHP_INI_REDIS=On
    - PHP_INI_APCU=On
    - PHP_INI_APD=On
    - PHP_FPM_PM=static
    - PHP_FPM_PM_MAX_CHILDREN=5
    - PHP_FPM_PM_START_SERVERS=20
    - PHP_FPM_PM_MIN_SPARE_SERVERS=5
    - PHP_FPM_PM_MAX_SPARE_SERVERS=33
    - PHP_FPM_PM_MAX_REQUESTS=500
    - USER_ID=
    - GROUP_ID=
